# force reexecuting the snapd snap version on the live system
# while developping features that only lands on edge, even if the
# deb version is higher.
# This allows automated tests to always run what’s next.
#[Service]
#Environment="SNAP_REEXEC=force"
