# When booting the live ISO, snapd seeding takes a while to complete, which
# can cause GDM to start before the Ubuntu installer is seeded and ready to be
# launched. This leads to a confusing delay between the user leaving Plymouth 
# and seeing the desktop wallpaper and the installer launching.
# This drop-in delays display-manager.service until snapd seeding completes, so 
# the installer launches within seconds of Plymouth disappearing.
[Unit]
After=snapd.seeded.service
